### ISSUE TITLE
New Raspberry Pi 3 Model B+ Pins

### ISSUE THREAD

**Issue by shatteredsword** [Gadgetoid/Pinout.xyz#274]
please add the 4 new pins for the model B+

**Comment by Gadgetoid** [comment]
They are just the POE taps from the RJ45 connector, which you can find documented here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_3bplus_1p0_reduced.pdf

I think they may be out of scope for Pinout.xyz since they only serve one, very advanced purpose. I'm surprised they are even populated at all on consumer boards, they're awkward!
