### ISSUE TITLE
I2S not I2C

### ISSUE THREAD

**Issue by urfdvw** [Gadgetoid/Pinout.xyz#407]
For the DAC boards, the DAC interface is I2S, not I2C. Please fix the description sections.

**Comment by Gadgetoid** [comment]
I'm not sure if this was intended as an issue or some kind of challenge, but for future reference linking some examples sure would be helpful.

If you mean what I think you mean - this is intentional. The boards you mention *do* communicate over i2c.

The "Details" sections are auto-generated based upon the usage/mode of pins, and perhaps there's a case to add I2S here, but the I2C entries are not a mistake.

**Comment by urfdvw** [comment]
As is pointed out in the diagram on page https://pinout.xyz/pinout/pirate_audio_headphone_amp.

I2C pins GPIO2 and 3 are NOT used. But I2S pins GPIO 18, 19, 21 are in use.

The same info is given on Pirate Audio's page here: https://shop.pimoroni.com/products/pirate-audio-headphone-amp
![image](https://user-images.githubusercontent.com/17154432/116245655-2cb48500-a737-11eb-81f5-38b2282c0c8e.png)

The same issue also appeared on:
https://pinout.xyz/pinout/pirate_audio_3w_amp
https://pinout.xyz/pinout/pirate_audio_line_out
https://pinout.xyz/pinout/pirate_audio_speaker

Why do I need to challenge you? I am a user of the board, I am here to offer help to improve the accuracy.

**Comment by lurch** [comment]
> As is pointed out in the diagram on page https://pinout.xyz/pinout/pirate_audio_headphone_amp

Yup, looks like e.g. https://github.com/Gadgetoid/Pinout.xyz/blob/master/src/en/overlay/pimoroni-pirate-audio-headphone-amp.md should say "I2S DAC" rather than "I2C DAC".

BTW there appears to be another "bug" on https://pinout.xyz/pinout/pirate_audio_headphone_amp too - the pinout diagram on the left shows "GPIO 24 (Button Y)" and "GPIO 20 (Button Y (Old))", but the text on the right says "On older boards you might find button Y on GPIO 20. On newer boards this has been moved to GPIO 18 to free up PCM Data-in." ? :confused: 
Maybe somebody mixed up their pin-numbers and GPIO-numbers in https://github.com/Gadgetoid/Pinout.xyz/commit/88c393f2fedcbc394eb05d09c661bea230af2193 :wink:

**Comment by Gadgetoid** [comment]
fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu

**Comment by Gadgetoid** [comment]
i r a profesionul
![image](https://user-images.githubusercontent.com/1746967/116256293-f85abc00-a76a-11eb-9092-c92d10f4b611.png)

**Comment by Gadgetoid** [comment]
> Maybe somebody mixed up their pin-numbers and GPIO-numbers in [88c393f](https://github.com/Gadgetoid/Pinout.xyz/commit/88c393f2fedcbc394eb05d09c661bea230af2193) wink

ugh I get as good as I give, huh

thanks @urfdvw you're right and I'm patching this now and will conduct self flagellation later by hitting the back of my throat with hot whiskey

**Comment by lurch** [comment]
> fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu

Sounds like you need a https://pinout.xyz/pinout/four_letter_phat :stuck_out_tongue_winking_eye:

**Comment by Gadgetoid** [comment]
Right I think this fix is published now! Thank you all
